# Generated by Django 3.2.9 on 2021-11-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pull_name', models.CharField(db_index=True, max_length=150, null=True)),
                ('reviewers_name', models.CharField(db_index=True, max_length=150)),
                ('assignees_name', models.CharField(db_index=True, max_length=150)),
                ('pull_url', models.CharField(db_index=True, max_length=150)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sirocaapp.userrequest')),
            ],
        ),
    ]
